# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'capybara/rspec'

require File.join(File.dirname(__FILE__), '../app')

Dir[File.dirname(__FILE__) + "/../i18n_dummy/**/*.rb"].each { |f| require f }
Dir[File.dirname(__FILE__) + "/support/**/*.rb"].each {|f| require f}

def fixture_path
  File.join(File.dirname(__FILE__), 'fixtures').to_s
end

Capybara.app = ::I18nDummyApp

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.order = 'random'
end
